FROM python:3.8.1-slim

COPY docker/ubuntu-deps.txt /tmp
RUN apt-get update && \
    apt-get install -y `grep -v '#' /tmp/ubuntu-deps.txt | xargs` && \
    rm -fr /var/lib/apt/lists/*

WORKDIR /tmp
ARG WATCHEXEC_VERSION=1.10.1
ARG WATCHEXEC_FILENAME=watchexec-$WATCHEXEC_VERSION-x86_64-unknown-linux-gnu
RUN curl -sL https://github.com/mattgreen/watchexec/releases/download/$WATCHEXEC_VERSION/$WATCHEXEC_FILENAME.tar.gz | tar -xz && \
    mv $WATCHEXEC_FILENAME/watchexec /usr/bin && \
    rm -rf $WATCHEXEC_FILENAME/watchexec

WORKDIR /work

COPY requirements.txt /work/
RUN pip3 install --no-cache-dir --no-dependencies -r requirements.txt
