name: build

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.GH_USERNAME }}/cats-bot/catsbot
        registry: docker.pkg.github.com
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: docker/Dockerfile.prod
        tags: latest
    - name: Deploy package to Vultr
      uses: appleboy/ssh-action@master
      env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.ID_RSA }}
        port: ${{ secrets.PORT }}
        envs: GITHUB_USERNAME, GITHUB_TOKEN
        script: |
          sudo podman stop $(sudo podman ps -a -q)
          sudo podman system prune -af
          sudo podman login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
          sudo podman pull docker.pkg.github.com/${{ secrets.GH_USERNAME }}/cats-bot/catsbot:latest
          sudo podman run -d --network host -p 8000:8000 docker.pkg.github.com/${{ secrets.GH_USERNAME }}/cats-bot/catsbot:latest
